# Generated by Django 4.2.3 on 2023-07-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigocate', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigouser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMenu',
            fields=[
                ('codigoestado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('codigoestado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('codigomenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombremenu', models.CharField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menutec.estadomenu')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('codigoplato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menutec.categoria')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menutec.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigopedido', models.AutoField(primary_key=True, serialize=False)),
                ('platoselec', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('codcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menutec.cliente')),
                ('codmenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menutec.menu')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menutec.estadopedido')),
            ],
        ),
    ]
