# Generated by Django 4.2.2 on 2023-07-10 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menutec', '0002_remove_pedido_platoselec'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
